using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Text.Json;

namespace Claude4Net.SDK
{
    public interface ITool
    {
        string Name { get; }
        string Description { get; }
        List<string>? Aliases => null;
        string? SearchHint => null;
        Task<object> ExecuteAsync(string arguments, object context);
    }

    public interface IToolRegistry
    {
        IReadOnlyList<ITool> GetTools();
        ITool? FindTool(string name);
    }

    public interface IUserApprovalHandler
    {
        Task<bool> RequestApprovalAsync(string toolName, string arguments);
    }

    public enum LLMStreamEventType { TextDelta, ThinkingDelta, ToolCallStart, Completed }

    public enum PermissionMode { Default, BypassPermissions, Yolo }

    public class ToolUseRequest
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; } = string.Empty;
        public object Input { get; set; } = new { };
    }

    public class ToolUseResult
    {
        public string ToolUseId { get; set; } = string.Empty;
        public string? CallId { get; set; } // The ID generated by the LLM
        public object? Content { get; set; }
        public bool IsError { get; set; }
    }

    public class LLMResponse
    {
        public string Text { get; set; } = string.Empty;
        public List<ToolUseRequest> ToolCalls { get; set; } = new();
    }

    public class LLMStreamEvent
    {
        public LLMStreamEventType Type { get; set; }
        public string? Delta { get; set; }
        public ToolUseRequest? ToolCall { get; set; }
        public LLMResponse? FinalResponse { get; set; }
    }

    // MCP Models
    public class McpTool
    {
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public object? InputSchema { get; set; }
    }

    public class McpCallToolResult
    {
        public List<McpContent> Content { get; set; } = new();
        public bool IsError { get; set; }
    }

    public class McpContent
    {
        public string Type { get; set; } = "text";
        public string Text { get; set; } = string.Empty;
    }

    // JSON-RPC Models
    public class JsonRpcRequest
    {
        public string Jsonrpc { get; set; } = "2.0";
        public string Method { get; set; } = string.Empty;
        public object? Params { get; set; }
        public object? Id { get; set; }
    }

    public class JsonRpcResponse
    {
        public string Jsonrpc { get; set; } = "2.0";
        public JsonElement? Result { get; set; }
        public JsonElement? Error { get; set; }
        public object? Id { get; set; }
    }

    public interface ILLMProvider
    {
        string Name { get; }
        IAsyncEnumerable<LLMStreamEvent> StreamQueryAsync(string prompt, string? model = null, System.Threading.CancellationToken ct = default);
        void AddMessage(object message);
    }
}
