<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Claude4Net.SDK\Claude4Net.SDK.csproj" />
    <ProjectReference Include="..\Claude4Net.Runtime\Claude4Net.Runtime.csproj" />
    <ProjectReference Include="..\Claude4Net.Commands\Claude4Net.Commands.csproj" />
    <ProjectReference Include="..\Claude4Net.Discord\Claude4Net.Discord.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Spectre.Console" Version="0.55.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
